name: Continous integration

on:
  push:
    branches: master

  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Build
        run: invoke preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: online
          publish_dir: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
